spring:
  application:
    name: datadog-worker
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localstack:4566

aws:
  region: us-east-1
  endpoint: http://localstack:4566
